jobs:
  include:
    - stage: "Tests"
      language: python
      sudo: true
      dist: xenial
      python: '2.7'
      install:
        - pip install -r requirements_dev.txt
        - pip install tox-travis
      script:
        - tox
        - coverage combine
        - coverage report -m
    - language: python
      sudo: true
      dist: xenial
      python: '3.4'
      install:
        - pip install -r requirements_dev.txt
        - pip install tox-travis
      script:
        - tox
        - coverage combine
        - coverage report -m
    - language: python
      sudo: true
      dist: xenial
      python: '3.5'
      install:
        - pip install -r requirements_dev.txt
        - pip install tox-travis
      script:
        - tox
        - coverage combine
        - coverage report -m
    - language: python
      sudo: true
      dist: xenial
      python: '3.6'
      install:
        - pip install -r requirements_dev.txt
        - pip install tox-travis
      script:
        - tox
        - coverage combine
        - coverage report -m
      after_success:
        - coveralls
    - language: python
      sudo: true
      dist: xenial
      python: '3.7'
      install:
        - pip install -r requirements_dev.txt
        - pip install tox-travis
      script:
        - tox
        - coverage combine
        - coverage report -m
    - stage: "Deploy"
      language: python
      script: skip
      deploy:
        provider: pypi
        user: tablethotels
        password:
          secure: ZN0+sFH1gto80kNhi32cBraACQ4ufbE4Hc28D2btNLu/PseWb07Xg1KPKwKyejjVvKthXpRVNltz/c5WypSCMJx5jfYuKT3+1r0/gpbRo3hDQ5Y97ovnJ4SJwiO3HCvD94DZtyE9ILksr+dX1WkERxAM3r4ZLDezMbPyY8poUP7ZUynHoED3u7XK4Eyh0tsNdRoh4uWGYhRXUPGTzltKvhXh6kzTvHOhnDKgSlfKJjsVQgAMoDnGNEIs82snZSfreBNPFwN28bpOP43wldWSlyOPH84KpvORDHGDG7VoGfN+4+K38TQPv9D6LBUHN99T/Ya3Kna3iAkilv6/JJD1z9cyudrVmqtb0TfFb8MM5ewKZP9wFhIqDD3hd8NYJOlgeA/V1P2oxigYAB6U1w0AwW7Ygc5/2TG5ibcWX4Ny+9zz9//+KDA0x5sL4fs9D3Bka3pQ9hUu6GCnnmn5TthiwqOpwNHYoVEvGTqfJMwdIX4iWUKO7qYIVlq/bh4alj3zr242Hz+0qiHNxTpudCKD2SyvbLA9KCgrtTbJrGJlGlFXRkGN2qMSCLX6DbexF++ZbsVSDqJyEZWpHeqR1CW79sLYyfT+sx6+PJKjbY7tDvir0yJ0Anfm5+ytYnA55FDTynl07MAr/Y9OcoYPFHoXEpaJL22Knntw48XmuF7u574=
        on:
          tags: true
        skip_existing: true
